spring:
  application:
    name: open-weekend

  # config:
  #   activate:
  #     on-profile: dev

  datasource:
    driverClassName: org.postgresql.Driver
    url: bold-glade.small-respect-production.svc.pipeops.internal
    username: postgres
    password: 8613d89c70253db94c2399c52

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  error:
    include-message: always


jwt:
  secret: "[a-zA-Z0-9._]^*$JwtSecretForOpenWeekendAndOtherSymbols"